<!-- PAGE RELATED PLUGIN(S) -->
<script src="js/plugin/datatables/jquery.dataTables.min.js"></script>
<script src="js/plugin/datatables/dataTables.colVis.min.js"></script>
<script src="js/plugin/datatables/dataTables.tableTools.min.js"></script>
<script src="js/plugin/datatables/dataTables.bootstrap.min.js"></script>
<script src="js/plugin/datatable-responsive/datatables.responsive.min.js"></script>

<script type="text/javascript">

// DO NOT REMOVE : GLOBAL FUNCTIONS!

$(document).ready(function() {
	

	/* BASIC ;*/
		var responsiveHelper_dt_basic = undefined;
		var responsiveHelper_datatable_fixed_column = undefined;
		var responsiveHelper_datatable_col_reorder = undefined;
		var responsiveHelper_datatable_tabletools = undefined;
		
		var breakpointDefinition = {
			tablet : 1024,
			phone : 480
		};

		$('#dt_basic').dataTable({
			"sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>"+
				"t"+
				"<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
			"autoWidth" : true,
			"preDrawCallback" : function() {
				// Initialize the responsive datatables helper once.
				if (!responsiveHelper_dt_basic) {
					responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
				}
			},
			"rowCallback" : function(nRow) {
				responsiveHelper_dt_basic.createExpandIcon(nRow);
			},
			"drawCallback" : function(oSettings) {
				responsiveHelper_dt_basic.respond();
			}
		});

	/* END BASIC */
	
	/* COLUMN FILTER  */
    var otable = $('#datatable_fixed_column').DataTable({
    	//"bFilter": false,
    	//"bInfo": false,
    	//"bLengthChange": false
    	//"bAutoWidth": false,
    	//"bPaginate": false,
    	//"bStateSave": true // saves sort state using localStorage
		"sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6 hidden-xs'f><'col-sm-6 col-xs-12 hidden-xs'<'toolbar'>>r>"+
				"t"+
				"<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
		"autoWidth" : true,
		"preDrawCallback" : function() {
			// Initialize the responsive datatables helper once.
			if (!responsiveHelper_datatable_fixed_column) {
				responsiveHelper_datatable_fixed_column = new ResponsiveDatatablesHelper($('#datatable_fixed_column'), breakpointDefinition);
			}
		},
		"rowCallback" : function(nRow) {
			responsiveHelper_datatable_fixed_column.createExpandIcon(nRow);
		},
		"drawCallback" : function(oSettings) {
			responsiveHelper_datatable_fixed_column.respond();
		}		
	
    });
    
    // custom toolbar
    $("div.toolbar").html('<div class="text-right"><img src="img/logo.png" alt="SmartAdmin" style="width: 111px; margin-top: 3px; margin-right: 10px;"></div>');
    	   
    // Apply the filter
    $("#datatable_fixed_column thead th input[type=text]").on( 'keyup change', function () {
    	
        otable
            .column( $(this).parent().index()+':visible' )
            .search( this.value )
            .draw();
            
    } );
    /* END COLUMN FILTER */   

	/* COLUMN SHOW - HIDE */
	$('#datatable_col_reorder').dataTable({
		"sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'C>r>"+
				"t"+
				"<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
		"autoWidth" : true,
		"preDrawCallback" : function() {
			// Initialize the responsive datatables helper once.
			if (!responsiveHelper_datatable_col_reorder) {
				responsiveHelper_datatable_col_reorder = new ResponsiveDatatablesHelper($('#datatable_col_reorder'), breakpointDefinition);
			}
		},
		"rowCallback" : function(nRow) {
			responsiveHelper_datatable_col_reorder.createExpandIcon(nRow);
		},
		"drawCallback" : function(oSettings) {
			responsiveHelper_datatable_col_reorder.respond();
		}			
	});
	
	/* END COLUMN SHOW - HIDE */

	/* TABLETOOLS */
	$('#datatable_tabletools').dataTable({
		
		// Tabletools options: 
		//   https://datatables.net/extensions/tabletools/button_options
		"sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
				"t"+
				"<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
        "oTableTools": {
        	 "aButtons": [
             "copy",
             "csv",
             "xls",
                {
                    "sExtends": "pdf",
                    "sTitle": "SmartAdmin_PDF",
                    "sPdfMessage": "SmartAdmin PDF Export",
                    "sPdfSize": "letter"
                },
             	{
                	"sExtends": "print",
                	"sMessage": "Generated by SmartAdmin <i>(press Esc to close)</i>"
            	}
             ],
            "sSwfPath": "js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
        },
		"autoWidth" : true,
		"preDrawCallback" : function() {
			// Initialize the responsive datatables helper once.
			if (!responsiveHelper_datatable_tabletools) {
				responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#datatable_tabletools'), breakpointDefinition);
			}
		},
		"rowCallback" : function(nRow) {
			responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
		},
		"drawCallback" : function(oSettings) {
			responsiveHelper_datatable_tabletools.respond();
		}
	});
	
	/* END TABLETOOLS */

})

</script>

<article class="col-sm-12 col-md-12 col-lg-12">

	<!-- Widget ID (each widget will need unique ID)-->
	<div class="jarviswidget jarviswidget-color-darken" id="wid-id-1" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-deletebutton="false">
	<header>
		<span class="widget-icon"> <i class="fa fa-file-text-o"></i></span>
		<h2>Data Peruntukan</h2>
	</header>

		<!-- widget div-->
		<div class="smart-form">
			
			<div class="widget-body no-padding">
				<fieldset>
					<div class="row">
						<section class="col col-sm-12 col-md-12 col-lg-12" style="overflow:auto">
							<table id="datatable_fixed_column" class="table table-striped table-bordered" width="100%">
					
						        <thead>
									
						            
						            <tr>
					                    <th>No.</th>
					                    <th>Deskripsi</th>
					                    <th>Jenis</th>
					                    <th>Luas</th>
					                    <th>Sertifikasi</th>
					                    <th>Pemilik</th>
					                    <th>Jenis Sertifikat</th>
					                    <th>No. Sertifikat</th>
					                    <th>Masa Berlaku</th>
					                    <th>Luas Sertifikat</th>
					                    <th>Tgl. Sertifikat</th>
					                    <th>No. SK</th>
					                    <th>Tgl. SK</th>
					                    <th>SKPD</th>
					                    <th>Keterangan</th>
					                    <th>Status Sertifikat</th>
					                    <th>Status Plang</th>
					                    <th>Status Penggunaan</th>
					                    <th>Sensus Fasos</th>
					                    <th>Jenis Fasos</th>
					                    <th>Status Laporan Keuangan</th>
					                    <th>Status Recon</th>
					                    <th>No. Dokumen Acuan</th>
					                    <th>No. BAST</th>
					                    <th>ID Aset</th>
					                    <th>Act.</th>
						            </tr>
						            <tr>
					                    <th><i class="fa fa-search"></i></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Deskripsi" /></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Jenis" /></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Luas" /></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Sertifikasi" /></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Pemilik" /></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Jenis Sertifikat" /></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="No. Sertifikat" /></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Masa Berlaku" /></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Luas Sertifikat" /></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Tgl. Sertifikat"/></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="No. SK"/></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Tgl. SK"/></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="SKPD"/></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Keterangan"/></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Status Sertifikat"/></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Status Plang"/></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Status Penggunaan"/></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Sensus Fasos"/></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Jenis Fasos"/></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Status Laporan Keuangan"/></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="Status Recon"/></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="No. Dokumen Acuan"/></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="No. BAST"/></label></th>
					                    <th><label class="input em15"><input type="text" class="form-control" placeholder="ID Aset"/></label></th>
					                    <th></th>
						            </tr>
						        </thead>
						        <tbody>
						        <?php
						        	$query=mysql_query("select * from peruntukan");
						        	$no=0;
						        	while($data=mysql_fetch_array($query)){
						        		$no++;
						        		echo"
						        			<tr>
							                    <td>$no</td>
							                    <td>$data[deskripsi]</td>
							                    <td>$data[jenis]</td>
							                    <td>$data[luas]</td>
							                    <td>$data[sertifikasi]</td>
							                    <td>$data[pemilik]</td>
							                    <td>$data[jenissertifikat]</td>
							                    <td>$data[nosertifikat]</td>
							                    <td>$data[masaberlaku]</td>
							                    <td>$data[luassertifikat]</td>
							                    <td>$data[tglsertifikat]</td>
							                    <td>$data[nosk]</td>
							                    <td>$data[tglsk]</td>
							                    <td>$data[skpd]</td>
							                    <td>$data[keterangan]</td>
							                    <td>$data[statussertifikat]</td>
							                    <td>$data[statusplang]</td>
							                    <td>$data[statuspenggunaan]</td>
							                    <td>$data[sensusfasos]</td>
							                    <td>$data[jenisfasos]</td>
							                    <td>$data[statuslaporankeuangan]</td>
							                    <td>$data[statusrecon]</td>
							                    <td>$data[nodokacuan]</td>
							                    <td>$data[nobast]</td>
							                    <td>$data[idaset]</td>
							                    <td></td>
								            </tr>
						        		";
						        	}
						        ?>
						            
						        </tbody>
						
							</table>
						</section>
						
					</div>
				</fieldset>
			</div>
		</div>
		<!-- end widget div -->

	</div>
	<!-- end widget -->

</article>
<!-- WIDGET END -->
